easytutoring/urls.py
from django.conf.urls import include, url 
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('usuarios.urls')),
    url(r'^faltas/', include('faltas.urls')),
    url(r'^forum/', include('forum.urls')),
    url(r'^aluno_area/', include('aluno_area.urls')),
    url(r'^turmas/', include('turmas.urls')),
    url(r'^resultados/', include('resultados.urls')),
    url(r'^assuntos/', include('assuntos.urls')),
    url(r'^questoes/', include('questoes.urls')),
    url(r'^questionarios/', include('questionarios.urls')),
    url(r'^disciplinas/', include('disciplinas.urls')),
    url(r'^professor_area/', include('professor_area.urls')),
    url(r'^tutor_area/', include('tutor_area.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.conf.urls import url

from . import views

app_name = 'forum'
urlpatterns = [
    url(r'^show/(?P<turma_id>[0-9]+)/$', views.show, name='show'),
    url(r'^new/(?P<turma_id>[0-9]+)/$', views.new, name='new'),
    url(r'^cadastrar_comentario', views.cadastrar_comentario, name='cadastrar_comentario'),
    url(r'^coments/(?P<post_id>[0-9]+)/$', views.coments, name='coments'),
    url(r'^excluir_post', views.excluir_post, name='excluir_post'),
    url(r'^excluir_comentario', views.excluir_comentario, name='excluir_comentario'),

    ]

questionarios/urls.py
from django.conf.urls import url

from . import views

app_name = 'questionarios'
urlpatterns = [
    url(r'^new', views.new, name='new'),
    url(r'^(?P<questionario_id>[0-9]+)/show', views.show, name='show'),
    url(r'^(?P<questionario_id>[0-9]+)/addquestao', views.addquestao, name='addquestao'),
    url(r'^(?P<questionario_id>[0-9]+)/assunto', views.assunto, name='assunto'),
    url(r'^todosQuestionarios', views.todosQuestionarios, name='todosQuestionarios'),
    url(r'^(?P<questionario_id>[0-9]+)/$', views.cadastrarQuestoes, name='cadastrarQuestoes'),
    url(r'^questoes/(?P<assunto_id>[0-9]+)/(?P<questionario_id>[0-9]+)/$', views.questoes, name='questoes'),]

questoes/urls.py
from django.conf.urls import url

from . import views

app_name = 'questoes'
urlpatterns = [
    url(r'^new', views.new, name='new'),
    ]

resultados/urls.py
from django.conf.urls import url

from . import views

app_name = 'resultados'
urlpatterns = [
    url(r'^index/(?P<questionario_id>[0-9]+)/$', views.index, name='index'),
    ]

questionarios/models.py
from django.db import models
from turmas.models import Turma
from usuarios.models import Professor
from usuarios.models import Tutor
from usuarios.models import Aluno
from questoes.models import Questao

# Create your models here.
class Questionario(models.Model):
	codigo = models.CharField(max_length=50)
	turma = models.ForeignKey(Turma,null=True)
	professor = models.ForeignKey(Professor)
	questoes = models.ManyToManyField(Questao)

questoes/models.py
from django.db import models
from assuntos.models import Assunto

# Create your models here.
class Questao(models.Model):
	enunciado = models.CharField(max_length=200,null=True)
	assunto = models.ForeignKey(Assunto)
	letra_a = models.CharField(max_length=200)
	letra_b = models.CharField(max_length=200)
	letra_c = models.CharField(max_length=200)
	letra_d = models.CharField(max_length=200)
	resposta = models.CharField(max_length=200)
	observacao = models.CharField(max_length=200)

	def __str__(self):
		return self.enunciado

questionarios/forms.py
from django import forms
from .models import Questionario
from turmas.models import Turma
from usuarios.models import Tutor,Aluno,Professor
from django.forms import ModelForm
from questoes.models import Questao
from assuntos.models import Assunto

class QuestionarioForm(forms.Form):
	codigo = forms.CharField( max_length=50)
	turma = forms.ModelChoiceField(queryset=Turma.objects.all())

	def is_valid(self):
		valid = True
		if not super(QuestionarioForm, self).is_valid():
			self.adiciona_erro('Não foi possível cadastrar a turma!')
			valid = False
		return valid
	def adiciona_erro(self, message):
		errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
		errors.append(message)

questoes/forms.py
from django import forms
from .models import Questao
from disciplinas.models import Disciplina
from assuntos.models import Assunto
from usuarios.models import Tutor,Aluno,Professor
from django.forms import ModelForm

class QuestaoForm(forms.Form):
	CHOICES = (('a', 'a'),('b', 'b'),('c', 'c'),('d', 'd'))
	enunciado = forms.CharField(max_length=200)
	assunto = forms.ModelChoiceField(queryset=Assunto.objects.all().order_by('nome'))
	letra_a = forms.CharField(max_length=200)
	letra_b = forms.CharField(max_length=200)
	letra_c = forms.CharField(max_length=200)
	letra_d = forms.CharField(max_length=200)
	resposta = forms.ChoiceField(choices=CHOICES,widget=forms.widgets.RadioSelect())
	observacao = forms.CharField(max_length=200)

	def is_valid(self):
		valid = True
		if not super(QuestaoForm, self).is_valid():
			self.adiciona_erro('Não foi possível cadastrar a turma!')
			valid = False
		return valid
	def adiciona_erro(self, message):
		errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
		errors.append(message)

questionarios/views.py
from django.shortcuts import  get_object_or_404, render,redirect
from usuarios.models import Usuario, Professor
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Permission
from disciplinas.models import Disciplina
from turmas.models import Turma
from disciplinas.forms import DisciplinaForm
from .models import Questionario
from .forms import QuestionarioForm
from questoes.forms import QuestaoForm
from questoes.models import Questao
from resultados.models import Resultado
from assuntos.models import Assunto
from assuntos.forms import AssuntoForm
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.http import HttpResponse
from django.http import JsonResponse
import json
from django.template.loader import render_to_string

def new(request):
	user = request.user
	usuario = Professor.objects.get(user=user)
	if request.user.has_perm('usuarios.pode_acessar_area_professor'):
		if request.method == 'POST':
			form = QuestionarioForm(request.POST)
			if form.is_valid():
				codigo = form.cleaned_data['codigo']
				turma = form.cleaned_data['turma']
				questionario = Questionario(codigo=codigo,turma=turma,professor=usuario)
				questionario.save()
				messages.add_message(request, messages.INFO, 'Questionario cadastrada com sucesso.')
				return HttpResponseRedirect('/professor_area/index.html')
			else:
				messages.add_message(request, messages.ERROR, 'Questionario já cadastrada.')

	form = QuestionarioForm()
	return render(request, 'questionarios/new.html', {'form': form, 'usuario':usuario})

def todosQuestionarios(request):
	user = request.user
	usuario = Professor.objects.get(user=user)
	questionarios = Questionario.objects.all()
	return render(request,'questionarios/todosQuestionarios.html',{'usuario':usuario,'questionarios':questionarios})

def assunto(request,questionario_id):
	a = request.GET.get('assunto', '')
	q = request.GET.get('questionario','')
	questionario = Questionario.objects.get(pk=questionario_id)
	assunto = Assunto.objects.get(nome=a)
	questoes = Questao.objects.filter(assunto_id=assunto)
	html = render_to_string('questionarios/questoes.html',{'assunto':assunto, 'questionario':questionario,'questoes':questoes})
	return HttpResponse(html)


def cadastrarQuestoes(request,questionario_id):
	user = request.user
	usuario = Professor.objects.get(user=user)
	questionario = Questionario.objects.get(pk=questionario_id)
	turma = questionario.turma
	disciplina = turma.disciplina
	assuntos = Assunto.objects.filter(disciplina_id=disciplina)
	# dados = {'codigo': questionario.codigo,'assunto':questionario.assunto ,'disciplina': questionario.disciplina, 'professor':questionario.professor, 'questoes':questionario.questoes.all()}

	return render(request, 'questionarios/cadastrarQuestoes.html', {'questionario':questionario,'assuntos':assuntos,'usuario':usuario})


def questoes(request,assunto_id,questionario_id):
	assunto = Assunto.objects.get(pk=assunto_id)
	questionario= Questionario.objects.get(pk=questionario_id)
	questoes = Questao.objects.filter(assunto_id=assunto)
	return render(request,'questionarios/questoes.html',{'assunto':assunto,'questionario':questionario,'questoes':questoes})

def addquestao(request,questionario_id):
	try:
		q = request.GET.get('question','')
		questao = Questao.objects.get(pk=q)
		quest = request.GET.get('questionario','')
		questionario = Questionario.objects.get(pk=quest)
		questionario.questoes.add(questao)
		questionario.save()
		exists = {
		'cadastrado': True,
		'message': 'Questão cadastrada com sucesso.'
		}
	except:
		exists = {
		'cadastrado': False,
		'message': 'Não foi possível cadastrar à questão.'
		}
	return JsonResponse(exists)

def show(request,questionario_id):
	user = request.user
	usuario = Professor.objects.get(user=user)
	questionario = Questionario.objects.get(pk=questionario_id)
	questoes = questionario.questoes.all()
	context = {'usuario':usuario,'questionario':questionario, 'questoes':questoes}
	return render(request,'questionarios/show.html',context=context)

questoes/views.py
from django.shortcuts import  get_object_or_404, render,redirect
from usuarios.models import Usuario, Professor
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Permission
from disciplinas.models import Disciplina
from disciplinas.forms import DisciplinaForm
from .models import Questao
from .forms import QuestaoForm
from django.http import HttpResponseRedirect
from django.contrib import messages
# Create your views here.

def new(request):
	user = request.user
	usuario = Professor.objects.get(user=user)
	if request.user.has_perm('usuarios.pode_acessar_area_professor'):
		if request.method == 'POST':
			form = QuestaoForm(request.POST)
			if form.is_valid():
				enunciado = form.cleaned_data['enunciado']
				assunto = form.cleaned_data['assunto']
				letra_a = form.cleaned_data['letra_a']
				letra_b = form.cleaned_data['letra_b']
				letra_c = form.cleaned_data['letra_c']
				letra_d = form.cleaned_data['letra_d']
				resposta = form.cleaned_data['resposta']
				observacao = form.cleaned_data['observacao']
				questao = Questao(enunciado=enunciado,assunto=assunto,letra_a=letra_a,letra_b=letra_b,letra_c=letra_c,letra_d=letra_d,resposta=resposta,observacao=observacao)
				questao.save()
				messages.add_message(request, messages.INFO, 'Questão cadastrada com sucesso.')
				return HttpResponseRedirect('/professor_area/index.html')
			else:
				messages.add_message(request, messages.ERROR, 'Questão já cadastrada.')

	form = QuestaoForm()
	return render(request, 'questoes/new.html', {'form': form, 'usuario':usuario})

templates/questionarios/cadastrarQuestoes.html
{% extends "professor_area/index.html" %}

{% block pageHeader %}
    <h2 class="page-header">Cadastrar Questões</h2>
{% endblock pageHeader %}
{% block form %}
<div class="form-group col-sm-8">

   <label id="lb-shift">Assuntos</label> <br>
   <div class="form-group col-sm-8">

       <select id="selecao" class="form-control">

        {% for assunto in assuntos %}
           <option >{{ assunto.nome }}</option>
        {% endfor %}
       </select>
      </div>        <button class="btn btn-default btn-login"  id="adicionar" type="button" style="magin:10px;"><i class="fa fa-search"></i>
      </button>

</div>      
<div id="results" class="form-group col-sm-12">
      
    </div>
{% endblock form %}


{% block javascript %}
 <script>
    $("#adicionar").click(function () {
      var assunto = $("#selecao").val();
      $.ajax({
        url: 'assunto',
        data: {
          'assunto': assunto,
          'questionario': {{questionario.id}}
        },
        success : function(html) {
             $('#results').html(html);
         }

      });

    });
</script>
{% endblock javascript %}

templates/questionarios/new.html
5{% extends "professor_area/index.html" %}
{% load widget_tweaks %}
{% block pageHeader %}
    <h2 class="page-header">Cadastrar Questionario
   <!--    <a data-toggle="modal" href="#cadastrarQuestao">
   <button class="btn btn-default btn-login"  id="adicionar" type="button"><i class="fa fa-plus"></i>
   </button></h2>
                         </a> -->

{% endblock pageHeader %}

{% block form %}
	<form action="{% url 'questionarios:new' %}" method="post">
		{% csrf_token %}
        <fieldset>
            <div class="form-group">
			        <label for="id_codigo">Título Do Questionário:</label>
			        {{form.codigo|add_class:"form-control"}}
            </div>
             <div class="form-group">
			        <label for="id_turma">Turma:</label>
			        {{form.turma|add_class:"form-control"}}
            </div>
<!--             <div class="form-group">
                    <label for="id_aluno">Alunos:</label>
                    {{form.alunos|add_class:"form-control"}}
</div>
 -->
            <center><input  type="submit" value="Cadastrar" class="btn btn-default btn-lg btn-login" /></center>
        </fieldset>
    </form>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" style="display:none;" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}


{% endblock form %}


{% block javascript %}
 <script>    
    $("#id_assunto").change(function () {
      var assunto = $(this).val();
      $.ajax({
        url: 'questionarios:assunto',
        data: {
          'assunto': assunto
        },
        dataType: 'json',
        success: function (exist_user) {
          if (exist_user.users) {
            $.notify({
            message: 'O usuário já existe, por favor utilize outro username!'
        },{
            type: 'pastel-warning',
            delay: 4000,
            template: '<div data-notify="container" class="col-xs-11 col-sm-3 alert alert-{0}" role="alert">' +
                '<span data-notify="title">{1}</span>' +
                '<span data-notify="message">{2}</span>' +
            '</div>'
        });
          }
        }
      });

    });
</script>
{% endblock javascript %}

templates/questionarios/questoes.html
    <hr>
    <center><h4><i class="fa fa-question" aria-hidden="true"></i>
Questões</h4></center>
    <div class="panel-body">
        <div class="table-responsive table-bordered">
            <table class="table">
                <thead>
                    <tr>
                        <th>Enunciado</th>
                        <th>Adicionar</th>

                    </tr>
                </thead>
                <tbody>
                	{% for questao in questoes %}
                        <tr id="{{questao.id}}">
                            <td>{{questao.enunciado}}</td>
    <td><input id="checar" type="checkbox"  value="{{questao.id}}" /></td>
                        </tr>
					{% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>

{% block javascript %}
 <script>
    $(document).ready(function() {
        $("tbody tr td #checar").click(function () {
          var question = $(this).val();
          $.ajax({
            url: 'addquestao',
            data: {
              'question': question,
              'questionario': {{questionario.id}},
              'assunto': {{assunto.id}}
            },
            success : function(exists) {
                var id = "#"+question
                 $(id).hide();
                if (exists.cadastrado) {
                  $.notify({
                  message: exists.message
                },{
                    type: 'pastel-success',
                    delay: 3000,
                    template: '<div data-notify="container" class="col-xs-11 col-sm-3 alert alert-{0}" role="alert">' +
                        '<span data-notify="title">{1}</span>' +
                        '<span data-notify="message">{2}</span>' +
                    '</div>'
                });
              }
               }

          });

        });
        });

</script>
{% endblock javascript %}

templates/questionarios/show.html
{% extends "professor_area/index.html" %}

{% load widget_tweaks %}

{% block pageHeader %}
    <h2 class="page-header">Informações Sobre O Questionário
    <a  href="{% url 'resultados:index' questionario.id %}"> <button style: "float: right;" type="button" class="btn btn-warning btn-circle btn-lg"><i class="fa fa-bar-chart-o  "></i>
                            </button></a></h2>
{% endblock pageHeader %}
{% block form %}
    <h4><b>Título: </b>{{ questionario.codigo }}</h4>
    <h4><b>Turma: </b>{{ questionario.turma }}</h4><hr>
    <center><h4>Questões</h4></center>
    {% for questao in questoes %}
        <h4>{{ questao.enunciado }}</h4>
            <li>{{questao.letra_a}}</li>
            <li>{{questao.letra_b}}</li>
            <li>{{questao.letra_c}}</li>
            <li>{{questao.letra_d}}</li>
            <hr>
    {% endfor %}
{% endblock form %}

templates/questionarios/todosQuestionarios.html
{% extends "professor_area/index.html" %}
{% load widget_tweaks %}
{% block pageHeader %}
    <h2 class="page-header">Todos Os Questionarios</h2>
{% endblock pageHeader %}

{% block form %}

    <div class="panel-body">
        <div class="table-responsive table-bordered">
            <table class="table">
                <thead>
                    <tr>
                        <th>Título</th>
                        <th>Criado por</th>
                        <th>Cadastrar Questões</th>
                        <th>Informações</th>
                    </tr>
                </thead>
                <tbody>
                	{% for questionario in questionarios %}
                        <tr>
                            <td>{{questionario.codigo}}</td>
                            <td>{{questionario.professor.nome_completo}}</td>
                            <td><a  href="{% url 'questionarios:cadastrarQuestoes' questionario.id %}"> <button type="button" class="btn btn-warning btn-circle"><i class="fa fa-plus"></i>
                            </button></a></td>
                            <td><a  href="{% url 'questionarios:show' questionario.id %}"> <button type="button" class="btn btn-warning btn-circle"><i class="fa fa-share"></i>
                            </button></a></td>
                        </tr>
					{% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>



{% endblock form %}