easytutoring/urls.py
from django.conf.urls import include, url 
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('usuarios.urls')),
    url(r'^faltas/', include('faltas.urls')),
    url(r'^forum/', include('forum.urls')),
    url(r'^aluno_area/', include('aluno_area.urls')),
    url(r'^turmas/', include('turmas.urls')),
    url(r'^resultados/', include('resultados.urls')),
    url(r'^assuntos/', include('assuntos.urls')),
    url(r'^questoes/', include('questoes.urls')),
    url(r'^questionarios/', include('questionarios.urls')),
    url(r'^disciplinas/', include('disciplinas.urls')),
    url(r'^professor_area/', include('professor_area.urls')),
    url(r'^tutor_area/', include('tutor_area.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

faltas/urls.py
from django.conf.urls import url

from . import views

app_name = 'faltas'
urlpatterns = [
    url(r'^new/(?P<turma_id>[0-9]+)/$', views.new, name='new'),
    url(r'^new/(?P<turma_id>[0-9]+)/cadastrarFrequencia', views.cadastrarFrequencia, name='cadastrarFrequencia'),
    url(r'^dadosFrequencia/(?P<turma_id>[0-9]+)/$', views.dadosFrequencia, name='dadosFrequencia'),
    url(r'^faltaAluno/(?P<turma_id>[0-9]+)/$', views.faltaAluno, name='faltaAluno'),
    ]

forum/urls.py
from django.conf.urls import url

from . import views

app_name = 'forum'
urlpatterns = [
    url(r'^show/(?P<turma_id>[0-9]+)/$', views.show, name='show'),
    url(r'^new/(?P<turma_id>[0-9]+)/$', views.new, name='new'),
    url(r'^cadastrar_comentario', views.cadastrar_comentario, name='cadastrar_comentario'),
    url(r'^coments/(?P<post_id>[0-9]+)/$', views.coments, name='coments'),
    url(r'^excluir_post', views.excluir_post, name='excluir_post'),
    url(r'^excluir_comentario', views.excluir_comentario, name='excluir_comentario'),

    ]

tutor_area/urls.py
from django.conf.urls import url

from . import views

app_name = 'tutor_area'
urlpatterns = [
    url(r'^index', views.index, name='index'),
    url(r'^todasTurmas', views.todasTurmas, name='todasTurmas'),
    url(r'^turmaArea/(?P<turma_id>[0-9]+)/$', views.turmaArea, name='turmaArea'),
    url(r'^listAlunos/(?P<turma_id>[0-9]+)/$', views.listAlunos, name='listAlunos'),]

usuarios/urls.py
from django.conf.urls import url

from . import views

app_name = 'usuarios'
urlpatterns = [
    url(r'^login', views.user_login, name='login'),
    url(r'^logout', views.user_logout, name='logout'),
    url(r'^new', views.new, name='new'),
    url(r'^arearestrita', views.restricted_area, name='restricted_area'),
    url(r'^index', views.index, name='index'),
    url(r'^$', views.index, name='index'),
    url(r'^validate_username', views.validate_username, name='validate_username'),
    url(r'^validate_email', views.validate_email, name='validate_email'),
    url(r'^validate_matricula', views.validate_matricula, name='validate_matricula'),
]

tutor_area/models.py
from django.db import models

# Create your models here.

tutor_area/views.py
from django.shortcuts import  get_object_or_404, render,redirect
from usuarios.models import Usuario, Professor, Aluno, Tutor
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Permission
from turmas.models import Turma
from disciplinas.models import Disciplina
from django.http import HttpResponseRedirect
from django.contrib import messages
from turmas.forms import TurmaForm

# Create your views here.
@login_required
def index(request):
	user = request.user
	usuario = Usuario.objects.get(user=user)
	turmas = Turma.objects.filter(tutor=usuario)

	context_dict = {'usuario': usuario,'turmas':turmas}
	if not request.user.is_authenticated :
		return redirect('%s?next=%s' % (settings.LOGIN_URL,request.path))
	verificaUsuario = verificarUsuario(request)
	return render(request, verificaUsuario,context_dict)



def verificarUsuario(request):
	if request.user.has_perm('usuarios.pode_acessar_area_professor'):
		return 'professor_area/index.html'
	elif request.user.has_perm('usuarios.pode_acessar_area_tutor'):
		return  'tutor_area/index.html'
	else:
		return 'aluno_area/index.html'

def todasTurmas(request):
	user = request.user
	usuario = Tutor.objects.get(user=user)
	if request.user.has_perm('usuarios.pode_acessar_area_tutor'):
		turmas = Turma.objects.filter(tutor=usuario)
		return render(request, 'tutor_area/todasTurmas.html', {'turmas': turmas, 'usuario': usuario})
	else:
		verificaUsuario = verificarUsuario(request)
		return render(request, verificaUsuario)

def turmaArea(request,turma_id):
	user = request.user
	usuario = Usuario.objects.get(user=user)
	turma = Turma.objects.get(pk=turma_id)
	alunos = turma.alunos.all()
	return render(request, 'tutor_area/turmaArea.html', {'turma': turma, 'alunos': alunos, 'usuario':usuario})

def listAlunos(request,turma_id):
	user = request.user
	usuario = Usuario.objects.get(user=user)
	turma = Turma.objects.get(pk=turma_id)
	alunos = turma.alunos.all()
	context= {'turma': turma, 
	'alunos': alunos, 
	'usuario':usuario}
	return render(request, 'tutor_area/listAlunos.html', context=context)

templates/tutor_area/index.html
{% extends "templateEasyTutoring.html" %}

{% block title %}
        <title>Area do Tutor</title>
{% endblock title %}
{% block pageHeader %}
    <h2 class="page-header">Suas Turmas</h2>
{% endblock pageHeader %}

{% block principal %}
    <a class="navbar-brand navbar-insid" id="link-color" href="{% url 'tutor_area:index' %}">EASYTUTORING</a>
{% endblock principal %}
{% block barraLateral %}
                <div class="navbar-default sidebar navbar-inside" role="navigation" >
                <div class="sidebar-nav navbar-collapse navbar-inside" >
                    <ul class="nav navbar-inside" id="side-menu">
                        <br>
                       <center><p><img src="{{ usuario.thumb.url}}" class= "img-circle"/> </p></center>
                        <li class="itens-menu">
                            <a href="#" class="itens-menu" id="link-color" ><i class="fa fa-users"></i> Turmas<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-l navbar-insideevel navbar-inside" id="side-menu">
                                <li class="itens-menu"> 
                                    <a href="{% url 'tutor_area:todasTurmas'%}" id="link-color">Suas Turmas</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>

{% endblock barraLateral %}
{% block form %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" style="display:none;" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="table-responsive table-bordered">
            <table class="table">
                <thead>
                    <tr>
                        <th>Codigo da Turma</th>
                        <th>Disciplina</th>
                        <th>Professor</th>

                        <th>Entrar</th>
                    </tr>
                </thead>
                <tbody>
                    {% for turma in turmas %}
                        <tr>
                            <td>{{turma.codigo}}</td>
                            <td>{{turma.disciplina}}</td>
                            <td>{{ turma.professor }}</td>
                            <td><a  href="{% url 'tutor_area:turmaArea' turma.id %}"> <button type="button" class="btn btn-warning btn-circle"><i class="glyphicon glyphicon-new-window  
"></i>
        </button></a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>
                        <!-- /.panel-body -->
{% endblock form %}

{% block logout %}
 <li><a href="{% url 'usuarios:logout' %}" ><i class="fa fa-sign-out fa-fw"></i> Sair</a>
{% endblock logout %}

templates/tutor_area/listAlunos.html
{% extends "tutor_area/turmaArea.html" %}
{% block pageHeader %}
    <h2 class="page-header">Alunos</h2>
{% endblock pageHeader %}

{% block form %}
    <div class="panel-body">
        <div class="table-responsive table-bordered">
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Matricula</th>
                        <th>Nome Completo</th>
                        <th>Curso</th>
                    </tr>
                </thead>
                <tbody>
                	{% for aluno in alunos %}
                        <tr>
                            <td><img src="{{ aluno.thumb.url}}" style="width:40px; height:40px; border:1px solid black;" class= "img-circle"/></td>
                            <td>{{aluno.matricula}}</td>
                            <td>{{aluno.nome_completo}}</td>
                             <td>{{aluno.curso}}</td>

                        </tr>
					{% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>

{% endblock form %}

templates/tutor_area/todasTurmas.html
{% extends "tutor_area/index.html" %}
{% block principal %}
    <a class="navbar-brand" href="{% url 'tutor_area:index' %}" id="link-color">EASYTUTORING</a>
{% endblock principal %}

{% load widget_tweaks %}

{% block pageHeader %}
    <h2 class="page-header">Suas Turmas</h2>
{% endblock pageHeader %}
{% block form %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" style="display:none;" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="table-responsive table-bordered">
            <table class="table">
                <thead>
                    <tr>
                        <th>Codigo da Turma</th>
                        <th>Disciplina</th>
                        <th>Professor</th>

                        <th>Entrar</th>
                    </tr>
                </thead>
                <tbody>
                    {% for turma in turmas %}
                        <tr>
                            <td>{{turma.codigo}}</td>
                            <td>{{turma.disciplina}}</td>
                            <td>{{ turma.professor }}</td>
                            <td><a  href="{% url 'tutor_area:turmaArea' turma.id %}"> <button type="button" class="btn btn-warning btn-circle"><i class="glyphicon glyphicon-new-window  
"></i>
        </button></a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>
                        <!-- /.panel-body -->
{% endblock form %}

{% block javascript %}
       <script>
        $(".info").each(function () {
            var message = $('.info').text();
        $.notify({
            message: message,
        },{
            type: 'pastel-success',
            delay: 3000,
            template: '<div data-notify="container" class="col-xs-11 col-sm-3 alert alert-{0}" role="alert">' +
                '<span data-notify="title">{1}</span>' +
                '<span data-notify="message">{2}</span>' +
            '</div>'
        });


      });

    </script>
{% endblock javascript %}

templates/tutor_area/turmaArea.html
{% extends "templateEasyTutoring.html" %}

{% block title %}
        <title>Area do Tutor</title>
{% endblock title %}

{% block principal %}
    <a class="navbar-brand" href="{% url 'tutor_area:index' %}" id="link-color">EASYTUTORING</a>
{% endblock principal %}
{% block barraLateral %}
                <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <br>
                       <center><p><img src="{{ usuario.thumb.url}}" class= "img-circle"/> </p></center>
                        <li class="itens-menu">
                            <a href="#" id="link-color"><i class="fa fa-user"></i>  Alunos<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                               <li>
                                    <a href="{% url 'tutor_area:listAlunos' turma.id %}" id="link-color"> Ver</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>

                        <li class="itens-menu">
                            <a href="#" id="link-color"><i class="fa fa-list-alt" id="link-color"></i> Frequência<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">

                               <li>
                                    <a href="{% url 'faltas:new' turma.id%}"  id="link-color">Cadastrar Frequência</a>
                                </li>

                                <li>
                                    <a href="{% url 'faltas:dadosFrequencia' turma.id%}" id="link-color">Visualizar Frequências</a>
                                </li>
                                <li>
                                    <a href="#" id="link-color">Visualizar Dados Adicionais</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li class="itens-menu">
                            <a href="#" id="link-color"><i class="fa fa-commenting-o"></i> Forum<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{% url 'forum:show' turma.id%}"  id="link-color">Entrar</a>
                                </li>
                                <li>
                                    <a href="{% url 'forum:new' turma.id%}" id="link-color"> Criar Postagem</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" style="display:none;" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

{% endblock barraLateral %}
{% block logout %}
 <li><a href="{% url 'usuarios:logout' %}"><i class="fa fa-sign-out fa-fw"></i> Sair</a>
{% endblock logout %}
{% block javascript %}
       <script>
        $(".info").each(function () {
            var message = $('.info').text();
        $.notify({
            message: message,
        },{
            type: 'pastel-success',
            delay: 3000,
            template: '<div data-notify="container" class="col-xs-11 col-sm-3 alert alert-{0}" role="alert">' +
                '<span data-notify="title">{1}</span>' +
                '<span data-notify="message">{2}</span>' +
            '</div>'
        });


      });

    </script>
{% endblock javascript %}