aluno_area/urls.py
from django.conf.urls import url

from . import views

app_name = 'aluno_area'
urlpatterns = [
    url(r'^index', views.index, name='index'),
    url(r'^responderQuestionario/(?P<turma_id>[0-9]+)/(?P<questionario_id>[0-9]+)/verficarRespostas', views.verficarRespostas, name='verficarRespostas'),
    url(r'^todasTurmas', views.todasTurmas, name='todasTurmas'),
    url(r'^listQuestionarios/(?P<turma_id>[0-9]+)/$', views.listQuestionarios, name='listQuestionarios'),
    url(r'^responderQuestionario/(?P<turma_id>[0-9]+)/(?P<questionario_id>[0-9]+)/$', views.responderQuestionario, name='responderQuestionario'),
    url(r'^turmaArea/(?P<turma_id>[0-9]+)/$', views.turmaArea, name='turmaArea'),
    url(r'^listAlunos/(?P<turma_id>[0-9]+)/$', views.listAlunos, name='listAlunos'),]

easytutoring/urls.py
from django.conf.urls import include, url 
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('usuarios.urls')),
    url(r'^faltas/', include('faltas.urls')),
    url(r'^forum/', include('forum.urls')),
    url(r'^aluno_area/', include('aluno_area.urls')),
    url(r'^turmas/', include('turmas.urls')),
    url(r'^resultados/', include('resultados.urls')),
    url(r'^assuntos/', include('assuntos.urls')),
    url(r'^questoes/', include('questoes.urls')),
    url(r'^questionarios/', include('questionarios.urls')),
    url(r'^disciplinas/', include('disciplinas.urls')),
    url(r'^professor_area/', include('professor_area.urls')),
    url(r'^tutor_area/', include('tutor_area.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

faltas/urls.py
from django.conf.urls import url

from . import views

app_name = 'faltas'
urlpatterns = [
    url(r'^new/(?P<turma_id>[0-9]+)/$', views.new, name='new'),
    url(r'^new/(?P<turma_id>[0-9]+)/cadastrarFrequencia', views.cadastrarFrequencia, name='cadastrarFrequencia'),
    url(r'^dadosFrequencia/(?P<turma_id>[0-9]+)/$', views.dadosFrequencia, name='dadosFrequencia'),
    url(r'^faltaAluno/(?P<turma_id>[0-9]+)/$', views.faltaAluno, name='faltaAluno'),
    ]

forum/urls.py
from django.conf.urls import url

from . import views

app_name = 'forum'
urlpatterns = [
    url(r'^show/(?P<turma_id>[0-9]+)/$', views.show, name='show'),
    url(r'^new/(?P<turma_id>[0-9]+)/$', views.new, name='new'),
    url(r'^cadastrar_comentario', views.cadastrar_comentario, name='cadastrar_comentario'),
    url(r'^coments/(?P<post_id>[0-9]+)/$', views.coments, name='coments'),
    url(r'^excluir_post', views.excluir_post, name='excluir_post'),
    url(r'^excluir_comentario', views.excluir_comentario, name='excluir_comentario'),

    ]

usuarios/urls.py
from django.conf.urls import url

from . import views

app_name = 'usuarios'
urlpatterns = [
    url(r'^login', views.user_login, name='login'),
    url(r'^logout', views.user_logout, name='logout'),
    url(r'^new', views.new, name='new'),
    url(r'^arearestrita', views.restricted_area, name='restricted_area'),
    url(r'^index', views.index, name='index'),
    url(r'^$', views.index, name='index'),
    url(r'^validate_username', views.validate_username, name='validate_username'),
    url(r'^validate_email', views.validate_email, name='validate_email'),
    url(r'^validate_matricula', views.validate_matricula, name='validate_matricula'),
]

aluno_area/models.py
from django.db import models

# Create your models here.

aluno_area/views.py
from django.shortcuts import  get_object_or_404, render,redirect
from usuarios.models import Usuario, Professor, Aluno, Tutor
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Permission
from turmas.models import Turma
from disciplinas.models import Disciplina
from django.http import HttpResponseRedirect
from django.contrib import messages
from turmas.forms import TurmaForm
from questionarios.models import Questionario
from questionarios.forms import QuestionarioForm
from questoes.forms import QuestaoForm
from questoes.models import Questao
from resultados.models import Resultado
from assuntos.models import Assunto
from assuntos.forms import AssuntoForm
from django.http import JsonResponse
import json
from django.template.loader import render_to_string
from django.http import HttpResponse

@login_required
def index(request):
	user = request.user
	usuario = Usuario.objects.get(user=user)
	turmas = Turma.objects.filter(alunos__id=usuario.id)
	context_dict = {'usuario': usuario,'turmas':turmas}
	if not request.user.is_authenticated :
		return redirect('%s?next=%s' % (settings.LOGIN_URL,request.path))
		
	verificarUser = verificarUsuario(request)

	return render(request, verificarUser ,context=context_dict)

@login_required
def verificarUsuario(request):
	if request.user.has_perm('usuarios.pode_acessar_area_professor'):
		return 'professor_area/index.html'
	elif request.user.has_perm('usuarios.pode_acessar_area_tutor'):
		return  'tutor_area/index.html'
	else:
		return 'aluno_area/index.html'
@login_required
def todasTurmas(request):
	user = request.user
	usuario = Aluno.objects.get(user=user)
	if request.user.has_perm('usuarios.pode_acessar_area_aluno'):
		turmas = Turma.objects.filter(alunos__id=usuario.id)
		return render(request, 'aluno_area/todasTurmas.html', {'turmas': turmas, 'usuario': usuario})
	else:
		verificaUsuario = verificarUsuario(request)
		return render(request, verificaUsuario)

def turmaArea(request,turma_id):
	user = request.user
	usuario = Usuario.objects.get(user=user)
	turma = Turma.objects.get(pk=turma_id)
	alunos = turma.alunos.all()
	return render(request, 'aluno_area/turmaArea.html', {'turma': turma, 'alunos': alunos, 'usuario':usuario})

def listAlunos(request,turma_id):
	user = request.user
	usuario = Usuario.objects.get(user=user)
	turma = Turma.objects.get(pk=turma_id)
	alunos = turma.alunos.all()
	context= {'turma': turma, 
	'alunos': alunos, 
	'usuario':usuario}
	return render(request, 'aluno_area/listAlunos.html', context=context)

def listQuestionarios(request,turma_id):
	user = request.user
	usuario = Usuario.objects.get(user=user)
	turma = Turma.objects.get(pk=turma_id)
	professor= turma.professor
	questionarios = Questionario.objects.filter(professor_id=professor,turma_id=turma)
	context= {'questionarios':questionarios,
	'usuario':usuario,
	'turma':turma}
	return render(request,'aluno_area/listQuestionarios.html',context=context)

def responderQuestionario(request,turma_id,questionario_id):
	user = request.user
	usuario = Usuario.objects.get(user=user)
	turma = Turma.objects.get(pk=turma_id)
	questionario = Questionario.objects.get(pk=questionario_id)
	questoes = questionario.questoes.all()
	context= {'questionario':questionario,
	'usuario':usuario,
	'turma':turma,
	'questoes':questoes}
	return render(request,'aluno_area/responderQuestionario.html',context=context)

def verficarRespostas(request,turma_id,questionario_id):
	user = request.user
	usuario = Aluno.objects.get(user=user)
	turma = Turma.objects.get(pk=turma_id)
	questionario = Questionario.objects.get(pk=questionario_id)
	questoes = questionario.questoes.all()
	results = request.POST.getlist('results[]')
	ids = request.POST.getlist('ids[]')
	questoes_erradas =  []
	for id in range(len(ids)):
		q= Questao.objects.get(pk=ids[id])
		resposta = results[id]
		if q.resposta != resposta:
			questoes_erradas.append(q)

	exists = Resultado.objects.filter(questionario=questionario,aluno=usuario).exists()
	if exists == False:
		resultado = Resultado(questionario=questionario,aluno=usuario)
		resultado.save()
		resultado.questoes_erradas = questoes_erradas
		resultado.save()
	context= {'results':results,
	'turma':turma,
	'questionario':questionario, 
	'questoes_erradas':questoes_erradas,
	'erradas': len(questoes_erradas),
	'total': len(results)}
	html = render_to_string('aluno_area/verficarRespostas.html', context=context)
	return HttpResponse(html)

templates/aluno_area/index.html
{% extends "templateEasyTutoring.html" %}

{% block title %}
        <title>Area do Aluno</title>
{% endblock title %}
{% block principal %}
    <a class="navbar-brand" href="{% url 'aluno_area:index' %}" id="link-color">EASYTUTORING</a>
{% endblock principal %}

{% block barraLateral %}
               <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <br>
                       <center><p><img src="{{ usuario.thumb.url}}" class= "img-circle"/> </p></center>
                        <li class="itens-menu">
                            <a href="#" id="link-color"><i class="fa fa-users"></i> Turmas<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{% url 'aluno_area:todasTurmas'%}" id="link-color">Buscar Turma</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>

                        
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>

{% endblock barraLateral %}
{% block pageHeader %}
    <h2 class="page-header">Suas Turmas</h2>
{% endblock pageHeader %}
{% block form %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" style="display:none;" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="table-responsive table-bordered">
            <table class="table">
                <thead>
                    <tr>
                        <th>Codigo da Turma</th>
                        <th>Tutor Responsável</th>
                        <th>Entrar</th>
                    </tr>
                </thead>
                <tbody>
                    {% for turma in turmas %}
                        <tr>
                            <td>{{turma.codigo}}</td>
                            <td>{{turma.tutor}}</td>
                            <td><a  href="{% url 'aluno_area:turmaArea' turma.id %}"> <button type="button" class="btn btn-warning btn-circle"><i class="fa fa-share"></i>
        </button></a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>
                        <!-- /.panel-body -->
{% endblock form %}

{% block logout %}
 <li><a href="{% url 'usuarios:logout' %}"><i class="fa fa-sign-out fa-fw"></i> Sair</a>
{% endblock logout %}

templates/aluno_area/listAlunos.html
{% extends "aluno_area/turmaArea.html" %}
{% block pageHeader %}
    <h2 class="page-header">Colegas de Turma</h2>
{% endblock pageHeader %}

{% block form %}
    <div class="panel-body">
        <div class="table-responsive table-bordered">
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nome Completo</th>
                        <th>Curso</th>
                    </tr>
                </thead>
                <tbody>
                	{% for aluno in alunos %}
                        <tr>
                            <td><img src="{{ aluno.thumb.url}}" style="width:40px; height:40px; border:1px solid black;" class= "img-circle"/></td>
                            <td>{{aluno.nome_completo}}</td>
                             <td>{{aluno.curso}}</td>

                        </tr>
					{% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>

{% endblock form %}

templates/aluno_area/listQuestionarios.html
{% extends "aluno_area/turmaArea.html" %}
{% block pageHeader %}
    <h2 class="page-header">Todos Os Questionarios</h2>
{% endblock pageHeader %}

{% block form %}
    <div class="panel-body">
        <div class="table-responsive table-bordered">
            <table class="table">
                <thead>
                    <tr>
                        <th>Titulo</th>
                        <th>Criado Por</th>
                        <th>Responder</th>
                    </tr>
                </thead>
                <tbody>
                	{% for questionario in questionarios %}
                        <tr>
                            <td>{{ questionario.codigo }}</td>
                            <td>{{questionario.professor}}</td>
                            <td><a  href="{% url 'aluno_area:responderQuestionario' turma.id questionario.id %}"> <button type="button" class="btn btn-warning btn-circle"><i class="fa fa-share"></i>
                            </button></a></td>

                        </tr>
					{% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>

{% endblock form %}

templates/aluno_area/responderQuestionario.html
{% extends "aluno_area/index.html" %}
{% block pageHeader %}
    <h2 class="page-header">Questionario</h2>
{% endblock pageHeader %}

{% block form %}
<div id="questionario">
    <h4><b>Título: </b>{{ questionario.codigo }}</h4>
    <center><h4>Questões</h4></center>
<!--     {% for questao in questoes %}
   <p id="questao" ><b>{{ questao.enunciado }}</b> <br>
    <input name="{{questao.id}}" value="a" type="checkbox"> {{questao.letra_a}} <br>
    <input name="{{questao.id}}" value="b" type="checkbox"> {{questao.letra_b}} <br>
    <input name="{{questao.id}}" value="c"  type="checkbox"> {{questao.letra_c}} <br>
    <input name="{{questao.id}}" value="d" type="checkbox"> {{questao.letra_d}} <br>
        </p><hr>
{% endfor %}
 -->
<div class="loader"></div>

    {% for questao in questoes %}
       <p  ><b>{{ questao.enunciado }}</b> <br>
        <input id="checar" name="{{questao.id}}" value="a" type="RADIO">a) {{questao.letra_a}} <br>
        <input id="checar" name="{{questao.id}}" value="b" type="RADIO">b) {{questao.letra_b}} <br>
        <input id="checar" name="{{questao.id}}" value="c"  type="RADIO">c) {{questao.letra_c}} <br>
        <input id="checar" name="{{questao.id}}" value="d" type="RADIO">d) {{questao.letra_d}} <br>
            </p><hr>
    {% endfor %}
    <center><button class="btn btn-default btn-sm btn-login" id="submeter">Responder</button></center><br>
</div>

<div id="results" class="form-group col-sm-12">
      
    </div>

{% endblock form %}

{% block javascript %}

<script>
$(document).ready(function(){

    var checkedCheckboxes = [];
    var idsQuest = [];
    $('#submeter').click(function() {
        $('input').each(function(){
            if ($(this).is(':checked')) {
                checkedCheckboxes.push($(this).val())
                idsQuest.push($(this).attr('name'))

            }

        });    
            $.ajax({
            url: 'verficarRespostas',
             method: 'POST',
             data: {results: checkedCheckboxes, ids: idsQuest , csrfmiddlewaretoken: '{{ csrf_token }}'},
             success : function(html) {

                $('#questionario').hide();

                $('#results').html(html);

                }

          });

    });
});

</script>

{% endblock javascript %}

templates/aluno_area/todasTurmas.html
{% extends "aluno_area/index.html" %}

{% load widget_tweaks %}

{% block pageHeader %}
    <h2 class="page-header">Suas Turmas</h2>
{% endblock pageHeader %}
{% block form %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" style="display:none;" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="table-responsive table-bordered">
            <table class="table">
                <thead>
                    <tr>
                        <th>Codigo da Turma</th>
                        <th>Tutor Responsável</th>
                        <th>Entrar</th>
                    </tr>
                </thead>
                <tbody>
                    {% for turma in turmas %}
                        <tr>
                            <td>{{turma.codigo}}</td>
                            <td>{{turma.tutor}}</td>
                            <td><a  href="{% url 'aluno_area:turmaArea' turma.id %}"> <button type="button" class="btn btn-warning btn-circle"><i class="fa fa-share"></i>
        </button></a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>
                        <!-- /.panel-body -->
{% endblock form %}

{% block javascript %}
       <script>
        $(".info").each(function () {
            var message = $('.info').text();
        $.notify({
            message: message,
        },{
            type: 'pastel-success',
            delay: 3000,
            template: '<div data-notify="container" class="col-xs-11 col-sm-3 alert alert-{0}" role="alert">' +
                '<span data-notify="title">{1}</span>' +
                '<span data-notify="message">{2}</span>' +
            '</div>'
        });


      });

    </script>
{% endblock javascript %}

templates/aluno_area/turmaArea.html
{% extends "templateEasyTutoring.html" %}

{% block title %}
        <title>Area do Aluno</title>
{% endblock title %}

{% block principal %}
    <a class="navbar-brand" href="{% url 'aluno_area:index' %}" id="link-color">EASYTUTORING</a>
{% endblock principal %}
{% block barraLateral %}
                <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <br>
                       <center><p><img src="{{ usuario.thumb.url}}" class= "img-circle"/> </p></center>
                        <li class="itens-menu">
                            <a href="#" id="link-color"><i class="fa fa-sitemap fa-fw"></i> Informações da Turma<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                               <li class="itens-menu">
                                    <a href="{% url 'aluno_area:listAlunos' turma.id %}" id="link-color">Ver Turma</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li class="itens-menu">
                            <a href="#" id="link-color"><i class="fa fa-commenting-o" ></i>Forum<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{% url 'forum:show' turma.id%}"  id="link-color">Entrar</a>
                                </li>
                                <li>
                                    <a href="#" id="link-color">Criar Postagem</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li class="itens-menu">
                            <a href="#" id="link-color"><i class="fa fa-files-o"></i> Questionarios<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li  class="itens-menu">
                                    <a href="{% url 'aluno_area:listQuestionarios' turma.id %}" id="link-color">Todos os Questionários</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li class="itens-menu">
                            <a href="#" id="link-color"><i class="fa fa-list-alt"></i> Frequência<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li  class="itens-menu">
                                    <a href="{% url 'faltas:faltaAluno' turma.id %}" id="link-color">Visualizar Frequências</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>

                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>

{% endblock barraLateral %}
{% block logout %}
 <li><a href="{% url 'usuarios:logout' %}"><i class="fa fa-sign-out fa-fw"></i> Sair</a>
{% endblock logout %}

templates/aluno_area/verficarRespostas.html
<style>
	.bordas{
	padding: 10px;
	border-left: 2px solid #971A0E;
	border-right: 2px solid #A31C0F;
	border-top: 2px solid #C92212;
	border-bottom: 2px solid #EA2D1A;
	} 
.correta {
  background-image: -webkit-gradient( linear, left top, right top, color-stop(0, #1A8467), color-stop(0.15, #2BD5A6), color-stop(0.3, #156B53), color-stop(0.45, #156B53), color-stop(0.6, #156B53),color-stop(0.75, #156B53), color-stop(0.9, #156B53), color-stop(1, #1A8467) );
  color:transparent;
  -webkit-background-clip: text;
  background-clip: text;
}
</style>
 <div class="modal fade" id="resultado" >
  <div class="modal-dialog"  id="informacoes">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Resultado do Questionário</h4>
      </div>
      <div class="modal-body">
        {% if total == erradas %}
            <p>Você errou todas as questões, tente outra vez...</p>

        {% elif erradas == 0 %}
        	<p><b>Parabéns</b>, você acertou todas as questões.</p>
        {% else %}
        	<p>Você errou <b>{{erradas}}/{{total}}</b></p>
        {% endif %}
        <p> </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-sm btn-login" data-dismiss="modal">Fechar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div></div><!-- /.modal -->
{% for questao in questoes_erradas %}
	<div class="bordas"  >
	<h4>{{questao.enunciado}}</h4> <br>
	{% if questao.resposta == "a" %}
		<h5 class="correta">a){{questao.letra_a}}</h5>
		<h5>b) {{questao.letra_b}}</h5>
		<h5>c) {{questao.letra_c}}</h5>
		<h5>d) {{questao.letra_d}}</h5>
	{% elif questao.resposta == "b" %}
		<h5>a) {{questao.letra_a}}</h5>
		<h5 class="correta">b) {{questao.letra_b}}</h5>
		<h5>c) {{questao.letra_c}}</h5>
		<h5>d) {{questao.letra_d}}</h5>

	{% elif questao.resposta == "c" %}
		<h5>a) {{questao.letra_a}}</h5>
		<h5>b) {{questao.letra_b}}</h5>
		<h5 class="correta">c) {{questao.letra_c}}</h5>
		<h5>d) {{questao.letra_d}}</h5>

	{% else %}
		<h5>a) {{questao.letra_a}}</h5>
		<h5>b) {{questao.letra_b}}</h5>
		<h5>c){{questao.letra_c}}</h5>
		<h5 class="correta">d) {{questao.letra_d}}</h5>
	{% endif %}
	<hr>
	<h5 class="correta"><b>Nota:</b> {{questao.observacao}} </h5>
	</div><br>
{% endfor %}

{% block javascript %}

        <script>
                $('#resultado').modal();
        </script>

{% endblock javascript %}