easytutoring/urls.py
from django.conf.urls import include, url 
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('usuarios.urls')),
    url(r'^faltas/', include('faltas.urls')),
    url(r'^forum/', include('forum.urls')),
    url(r'^aluno_area/', include('aluno_area.urls')),
    url(r'^turmas/', include('turmas.urls')),
    url(r'^resultados/', include('resultados.urls')),
    url(r'^assuntos/', include('assuntos.urls')),
    url(r'^questoes/', include('questoes.urls')),
    url(r'^questionarios/', include('questionarios.urls')),
    url(r'^disciplinas/', include('disciplinas.urls')),
    url(r'^professor_area/', include('professor_area.urls')),
    url(r'^tutor_area/', include('tutor_area.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

faltas/urls.py
from django.conf.urls import url

from . import views

app_name = 'faltas'
urlpatterns = [
    url(r'^new/(?P<turma_id>[0-9]+)/$', views.new, name='new'),
    url(r'^new/(?P<turma_id>[0-9]+)/cadastrarFrequencia', views.cadastrarFrequencia, name='cadastrarFrequencia'),
    url(r'^dadosFrequencia/(?P<turma_id>[0-9]+)/$', views.dadosFrequencia, name='dadosFrequencia'),
    url(r'^faltaAluno/(?P<turma_id>[0-9]+)/$', views.faltaAluno, name='faltaAluno'),
    ]

forum/urls.py
from django.conf.urls import url

from . import views

app_name = 'forum'
urlpatterns = [
    url(r'^show/(?P<turma_id>[0-9]+)/$', views.show, name='show'),
    url(r'^new/(?P<turma_id>[0-9]+)/$', views.new, name='new'),
    url(r'^cadastrar_comentario', views.cadastrar_comentario, name='cadastrar_comentario'),
    url(r'^coments/(?P<post_id>[0-9]+)/$', views.coments, name='coments'),
    url(r'^excluir_post', views.excluir_post, name='excluir_post'),
    url(r'^excluir_comentario', views.excluir_comentario, name='excluir_comentario'),

    ]

turmas/urls.py
from django.conf.urls import url

from . import views

app_name = 'turmas'
urlpatterns = [
    url(r'^new', views.new, name='new'),
    url(r'^todasTurmas', views.todasTurmas, name='todasTurmas'),
    url(r'^autocomplete', views.autocomplete, name='autocomplete'),
    url(r'^adicionarAlunos', views.adicionarAlunos, name='adicionarAlunos'),
    url(r'^(?P<turma_id>[0-9]+)/$', views.edit, name='edit'),]

turmas/models.py
from django.db import models
from disciplinas.models import Disciplina
from usuarios.models import Professor
from usuarios.models import Tutor
from usuarios.models import Aluno
# Create your models here.
class Turma(models.Model):
	codigo = models.CharField(max_length=150)
	disciplina = models.ForeignKey(Disciplina, related_name='disciplinas',null=True)
	professor = models.ForeignKey(Professor, related_name='professores')
	tutor = models.ForeignKey(Tutor, related_name='tutores')
	alunos = models.ManyToManyField(Aluno, related_name='alunos')


	def __str__(self):
		return self.codigo

turmas/forms.py
from django import forms
from .models import Turma
from disciplinas.models import Disciplina
from usuarios.models import Tutor,Aluno
from django.forms import ModelForm

class TurmaForm(forms.Form):
	codigo = forms.CharField(label='codigo', max_length=150)
	disciplina = forms.ModelChoiceField(queryset=Disciplina.objects.all().order_by('nome'))
	tutor = forms.ModelChoiceField(queryset=Tutor.objects.all().order_by('nome_completo'))
	# alunos = forms.ModelMultipleChoiceField(queryset=Aluno.objects.all().order_by('nome_completo'))

	def is_valid(self):
		valid = True
		if not super(TurmaForm, self).is_valid():
			self.adiciona_erro('Não foi possível cadastrar a turma!')
			valid = False
		return valid

turmas/views.py
from django.shortcuts import  get_object_or_404, render,redirect
from usuarios.models import Usuario, Professor, Aluno, Tutor
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Permission
from .models import Turma
from disciplinas.models import Disciplina
from django.http import HttpResponseRedirect
from django.contrib import messages
from .forms import TurmaForm
from django.http import HttpResponse
from django.http import JsonResponse
import json

# Create your views here.
@login_required
def new(request):
	user = request.user
	usuario = Professor.objects.get(user=user)
	if request.method == 'POST':
		form = TurmaForm(request.POST)
		if form.is_valid():
			codigo = form.cleaned_data['codigo']
			disciplina = form.cleaned_data['disciplina']
			tutor = form.cleaned_data['tutor']
			# alunos = form.cleaned_data['alunos']
			nova_turma = Turma(codigo=codigo, disciplina=disciplina,tutor=tutor, professor=usuario)
			# nova_turma.save()
			# nova_turma.alunos = alunos
			nova_turma.save()
			messages.add_message(request, messages.INFO, 'Turma cadastrada com sucesso.')
			return HttpResponseRedirect('/professor_area/index.html')
		else:
			messages.add_message(request, messages.ERROR, 'Não foi possível cadastrar à turma.')

	form = TurmaForm()
	return render(request, 'turmas/new.html', {'form': form, 'usuario':usuario})

def todasTurmas(request):
	user = request.user
	usuario = Professor.objects.get(user=user)
	if request.user.has_perm('usuarios.disciplina'):
		t = Turma.objects.all()
		turmas=[]
		for turma in t :
			if turma.professor.id == usuario.id:
				turmas.append(turma)
		return render(request, 'turmas/todasTurmas.html', {'turmas': turmas, 'usuario': usuario})
	else:
		verificaUsuario = verificarUsuario(request)
		return render(request, verificaUsuario)

@login_required
def edit(request,turma_id):
	user = request.user
	usuario = Professor.objects.get(user=user)
	turma = Turma.objects.get(pk=turma_id)
	if request.method == "POST":
		form = TurmaForm(request.POST )
		if form.is_valid():
			codigo = form.cleaned_data['codigo']
			disciplina = form.cleaned_data['disciplina']
			tutor = form.cleaned_data['tutor']
			# alunos = form.cleaned_data['alunos']
			turma.codigo = codigo
			turma.disciplina = disciplina
			turma.tutor = tutor
			# turma.alunos = alunos
			messages.add_message(request, messages.INFO, 'Turma atualizada com sucesso.')
			turma.save()
			return redirect('/turmas/todasTurmas.html')
		else:
			messages.add_message(request, messages.ERROR, 'Não foi possível atualizar.')
	else:
		dados_turma = {'codigo': turma.codigo, 'disciplina': turma.disciplina, 'tutor':turma.tutor, 'alunos':turma.alunos.all()}
		form = TurmaForm(initial=dados_turma)
	return render(request, 'turmas/edit.html', {'form': form, 'turma':turma, 'usuario':usuario})



def verificarUsuario(request):
	if request.user.has_perm('usuarios.pode_acessar_area_professor'):
		return 'professor_area/index.html'
	elif request.user.has_perm('usuarios.pode_acessar_area_tutor'):
		return  'tutor_area/index.html'
	else:
		return 'aluno_area/index.html'


 
def autocomplete(request):
  if request.is_ajax():
    q = request.GET.get('term', '')
    alunos = Aluno.objects.filter(nome_completo__istartswith=q)
    results = []
    for aluno in alunos:
      aluno_json = {}
      aluno_json = aluno.nome_completo
      results.append(aluno_json)
    data = json.dumps(results)
  else:
    data = 'fail'
  mimetype = 'application/json'
  return HttpResponse(data, mimetype)

def adicionarAlunos(request):
	if request.is_ajax():
		nome = request.GET.get('nome','')
		try:
			aluno = Aluno.objects.get(nome_completo=nome)
			turma = request.GET.get('turma','')
			turmas = Turma.objects.get(pk=turma)
			turmas.alunos.add(aluno)
			turmas.save()
			exists = {
			'cadastrado': True,
			'message': 'O usuário foi adicionado à turma'
			}
		except:
			exists = {
			'cadastrado': False,
			'message': 'Não existem alunos com esse nome.'
			}

	else:
		exists = {
		'cadastrado': False,
		'message': 'oi'
		}
	return JsonResponse(exists)

templates/turmas/edit.html
{% extends "professor_area/index.html" %}
{% load static  %}

{% block ref %}
    <link href="{% static 'css/notify/bootstrap-notify.css' %}" rel="stylesheet" type="text/css">

<link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />
{% endblock ref %}
{% load widget_tweaks %}

{% block pageHeader %}
    <h2 class="page-header">Editar Turma</h2>
{% endblock pageHeader %}
{% block form %}
	{% if messages %}
	    <ul class="messages">
	        {% for message in messages %}
	        <li{% if message.tags %} class="{{ message.tags }}" style="display:none;" {% endif %}>{{ message }}</li>
	        {% endfor %}
	    </ul>
	{% endif %}
<div class="form-group input-group">
  <input type="text" id="texto" class="form-control">
  <span class="input-group-btn">
      <button class="btn btn-default btn-login"  id="adicionar" type="button"><i class="fa fa-plus"></i>
      </button>
  </span>
</div>
<!-- <div class="form-group">
  <label for="id_codigo">Adicionar Alunos:</label>
  <input id="texto" class="form-control" name="message_name" type="text" />
  <button id="adicionar"> submeter</button>
</div>
 -->
	<form action="{% url 'turmas:edit' turma.id %}" method="POST" enctype="multipart/form-data">
	{% csrf_token %}

            <div class="form-group">
                    <label for="id_codigo">Codigo Turma:</label>
                    {{form.codigo|add_class:"form-control"}}
            </div>
             <div class="form-group">
                    <label for="id_disciplina">Disciplina:</label>
                    {{form.disciplina|add_class:"form-control"|attr:"id:id_disciplina"}}
            </div>
            <div class="form-group">
                    <label for="id_tutor">Tutor:</label>
                    {{form.tutor|add_class:"form-control"}}
            </div>
<!--             <div class="form-group">
              <label for="id_aluno">Alunos:</label>
              {{form.alunos|add_class:"form-control"}}
      </div>
       -->      <center><input  type="submit" value="Editar" class="btn btn-default btn-lg btn-login" /></center>

</form>

{% endblock form %}

{% block javascript %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js"></script>

       <script>
        $(".error").each(function () {
            var message = $('.error').text();
        $.notify({
            message: message,
        },{
            type: 'pastel-danger',
            delay: 3000,
            template: '<div data-notify="container" class="col-xs-11 col-sm-3 alert alert-{0}" role="alert">' +
                '<span data-notify="title">{1}</span>' +
                '<span data-notify="message">{2}</span>' +
            '</div>'
        });


      });

    </script>

<script>
$(function() {
    $("#texto").autocomplete({
      source: "/turmas/autocomplete/",
      select: function (event, ui) { 
        AutoCompleteSelectHandler(event, ui)
      },
      minLength: 2,
    });
  });

  function AutoCompleteSelectHandler(event, ui)
  {
    var selectedObj = ui.item;
  }

</script>
    <script>    
    $("#adicionar").click(function () {
      var nome = $('#texto').val();
      $('#texto').val('');
      $.ajax({
        url: '/turmas/adicionarAlunos/',
        data: {
          'nome': nome,
          'turma': {{turma.id}}
        },
        dataType: 'json',
        success: function (exists) {
          if (exists.cadastrado) {
            $.notify({
            message: 'O usuário foi adicionado com sucesso!'
        },{
            type: 'pastel-success',
            delay: 1000,
            template: '<div data-notify="container" class="col-xs-11 col-sm-3 alert alert-{0}" role="alert">' +
                '<span data-notify="title">{1}</span>' +
                '<span data-notify="message">{2}</span>' +
            '</div>'
        });
          }
        else{
            $.notify({
            message: exists.message
        },{
            type: 'pastel-danger',
            delay: 1000,
            template: '<div data-notify="container" class="col-xs-11 col-sm-3 alert alert-{0}" role="alert">' +
                '<span data-notify="title">{1}</span>' +
                '<span data-notify="message">{2}</span>' +
            '</div>'
        });
          }
        }
      });

    });
</script>
    <script src="{% static 'js/notify/bootstrap-notify.js' %}"></script>
    <script src="{% static 'js/notify/bootstrap-notify.min.js' %}"></script>

{% endblock javascript %}

templates/turmas/new.html
{% extends "professor_area/index.html" %}

{% load widget_tweaks %}

{% block pageHeader %}
    <h2 class="page-header">Cadastrar Turmas</h2>
{% endblock pageHeader %}
{% block form %}
	<form action="{% url 'turmas:new' %}" method="post">
		{% csrf_token %}
        <fieldset>
            <div class="form-group">
			        <label for="id_codigo">Codigo Turma:</label>
			        {{form.codigo|add_class:"form-control"}}
            </div>
             <div class="form-group">
			        <label for="id_tutor">Disciplina:</label>
			        {{form.disciplina|add_class:"form-control"}}
            </div>
            <div class="form-group">
			        <label for="id_tutor">Tutor:</label>
			        {{form.tutor|add_class:"form-control"}}
            </div>
            <center><input  type="submit" value="Cadastrar" class="btn btn-default btn-lg btn-login" /></center>
        </fieldset>
    </form>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" style="display:none;" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}


{% endblock form %}

{% block javascript %}
       <script>
        $(".error").each(function () {
            var message = $('.error').text();
        $.notify({
            message: message,
        },{
            type: 'pastel-danger',
            delay: 3000,
            template: '<div data-notify="container" class="col-xs-11 col-sm-3 alert alert-{0}" role="alert">' +
                '<span data-notify="title">{1}</span>' +
                '<span data-notify="message">{2}</span>' +
            '</div>'
        });


      });

    </script>

{% endblock javascript %}

templates/turmas/todasTurmas.html
{% extends "professor_area/index.html" %}

{% load widget_tweaks %}

{% block pageHeader %}
    <h2 class="page-header">Suas Turmas</h2>
{% endblock pageHeader %}
{% block form %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" style="display:none;" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="table-responsive table-bordered">
            <table class="table">
                <thead>
                    <tr>
                        <th>Codigo da Turma</th>
                        <th>Tutor Responsável</th>
                        <th>Editar</th>
                        <th>Frequência</th>
                    </tr>
                </thead>
                <tbody>
                	{% for turma in turmas %}
                        <tr>
                            <td>{{turma.codigo}}</td>
                            <td>{{turma.tutor}}</td>
                            <td><a  href="{% url 'turmas:edit' turma.id %}"> <button type="button" class="btn btn-warning btn-circle"><i class="fa fa-edit"></i>
                            </button></a></td>
                            <td><a  href="{% url 'faltas:dadosFrequencia' turma.id %}"> <button type="button" class="btn btn-warning btn-circle"><i class="fa fa-list-alt"></i>
                             </button></a></td>
                        </tr>
					{% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>

{% endblock form %}

{% block javascript %}
       <script>
        $(".info").each(function () {
            var message = $('.info').text();
        $.notify({
            message: message,
        },{
            type: 'pastel-success',
            delay: 3000,
            template: '<div data-notify="container" class="col-xs-11 col-sm-3 alert alert-{0}" role="alert">' +
                '<span data-notify="title">{1}</span>' +
                '<span data-notify="message">{2}</span>' +
            '</div>'
        });


      });

    </script>
{% endblock javascript %}